[project]
name = "can_re"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cantools>=42.0.3",
    "python-can>=4.6.1",
]

[project.optional-dependencies]
desktop = [
    "mcp>=1.28.1",
    "pygobject>=3.48.2; sys_platform == 'linux'",
    "pyinstaller>=6.21.0; sys_platform == 'win32'",
    "pywebview>=6.2.1",
]

[project.scripts]
can-re = "can_re.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel.force-include]
"plugins_dist" = "can_re/plugins"
